name: Validate JSON packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-jsons:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          name: Quaddicted/tools
          path: ./tools

      - name: Validate JSON packages
        run: QUADDICTED_DATA="${GITHUB_WORKSPACE}" python "${GITHUB_WORKSPACE}"/tools/tools/validate_jsons.py
