name: Validate JSON packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-jsons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: quaddicted-data

    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: Quaddicted/tools
        path: tools

    - name: Install validation requirements
      run: pip install -r ./tools/tools/requirements.txt

    - name: Validate JSON packages
      run: |
        LOGGING_LEVEL=ERROR \
        QUADDICTED_DATA=./quaddicted-data \
        python ./tools/tools/validate_jsons.py
