name: Validate JSON packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate-jsons:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: quaddicted-data

    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: Quaddicted/tools
        path: tools
        
    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        version: "0.12.3"
        activate-environment: "true"

    - name: Install validation requirements
      run: uv pip install -r ./tools/requirements.txt

    - name: Validate JSON packages
      run: |
        LOGGING_LEVEL=ERROR \
        uv run ./tools/scripts/validate_dir_of_jsons.py --directory ./quaddicted-data
